# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: workshop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001  # Accessible via <EC2-public-IP>:30001
  type: NodePort
  selector:
    role: api
