apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000  # Choose a port between 30000-32767
  type: NodePort
  selector:
    role: frontend