apiVersion: v1
kind: Secret
metadata:
  namespace: workshop
  name: mongo-sec
type: Opaque
data:
  username: YWRtaW4=  # base64 for 'admin'
  password: cGFzc3dvcmQxMjM=  # base64 for 'password123'
